version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      
      - run:
          name: build dependencies
          command: bundle install
          
      - run:
          name: build ins
          command: gem install unf_ext -v '0.0.9'

      - run:
          name: build jekyll
          command: bundle exec jekyll build

      - run:
          name: build the jekyll site
          command: date
