version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      
      - run:
          name: build dependencies
          command: echo Hello, World.

      - run:
          name: build the jekyll site
          command: date
